  SELECT 'MAE' AS COLUNA,
		 TABLE_NAME  AS 'Tabela',
         COLUMN_NAME AS 'Coluna'
    FROM INFORMATION_SCHEMA.COLUMNS
   WHERE COLUMN_NAME LIKE '%NOMEMAE%'

UNION ALL

SELECT	'PAI' AS COLUNA,
		TABLE_NAME  AS 'Tabela',
        COLUMN_NAME AS 'Coluna'
    FROM INFORMATION_SCHEMA.COLUMNS
   WHERE COLUMN_NAME LIKE '%NOMEPAI%'