
SELECT
	A.RA,
	P.NOME 'NOME_ALUNO',
	/*ISNULL(P.EMAIL, 'Não cadastrado') 'EMAIL',*/
	C.NOME 'NOME_CURSO',
	SC.DESCRICAO 'STATUS_CURSO',
	T.NOME 'TURNO',
	H.NOME 'HABILITACAO',
	G.DESCRICAO 'MATRIZ_CURRICULAR',
	CONVERT(VARCHAR(10), MPL.PERIODO) + ' Semestre' 'SEMESTRE',
	PL.CODPERLET 'PERIODO_LETIVO',
	MPL.CODTURMA 'TURMA_PERIODO_LETIVO',
	TM.DESCRICAO 'TIPO_MATRICULA_PERIODO_LETIVO',
	SPL.DESCRICAO 'STATUS_PERIODO_LETIVO',
	TD.CODTURMA 'TURMA_DISCIPLINA',
	TTD.NOME 'TURNO_DISCIPLINA',
	D.CODDISC 'CODIGO_DISCIPLINA',
	D.NOME 'NOME_DISCIPLINA',
	SM.DESCRICAO 'STATUS_DISCIPLINA',
	TMTD.DESCRICAO 'TIPO_MATRICULA_DISCIPLINA',
	RS.DESCRICAO 'RESULTADO_FINAL',
	M.NUMDIARIO 'NUMERO_DIARIO',
	1 'QUANTIDADE'
FROM
	/*-- Dados do aluno --*/ 
	SALUNO A
	INNER JOIN PPESSOA P (NOLOCK) ON P.CODIGO = A.CODPESSOA
	/*-- Dados da matricula no curso --*/
	INNER JOIN SHABILITACAOALUNO HA (NOLOCK) ON HA.RA = A.RA
	INNER JOIN SSTATUS SC (NOLOCK) ON SC.CODSTATUS = HA.CODSTATUS
	INNER JOIN SHABILITACAOFILIAL HF (NOLOCK) ON HF.IDHABILITACAOFILIAL = HA.IDHABILITACAOFILIAL
	INNER JOIN SCURSO C (NOLOCK) ON C.CODCURSO = HF.CODCURSO
	INNER JOIN STURNO T (NOLOCK) ON T.CODTURNO = HF.CODTURNO
	INNER JOIN SHABILITACAO H (NOLOCK) ON H.CODCURSO = HF.CODCURSO AND H.CODHABILITACAO = HF.CODHABILITACAO
	INNER JOIN SGRADE G (NOLOCK) ON G.CODCURSO = HF.CODCURSO AND G.CODHABILITACAO = HF.CODHABILITACAO 
					AND G.CODGRADE = HF.CODGRADE AND APLICACAO = 'S' /*S - CLASSIS.NET*/
	/*-- dados da matricula no período letivo --*/
	LEFT JOIN SMATRICPL MPL (NOLOCK) ON MPL.RA = HA.RA AND MPL.IDHABILITACAOFILIAL = HA.IDHABILITACAOFILIAL
	INNER JOIN SPLETIVO PL (NOLOCK) ON PL.IDPERLET = MPL.IDPERLET
	INNER JOIN STIPOMATRICULA TM (NOLOCK) ON TM.CODTIPOMAT = MPL.CODTIPOMAT
	INNER JOIN SSTATUS SPL (NOLOCK) ON SPL.CODSTATUS = MPL.CODSTATUS
	/*-- Dados da matricula na disciplina --*/
	LEFT JOIN SMATRICULA M (NOLOCK) ON M.RA = MPL.RA AND M.IDPERLET = MPL.IDPERLET AND M.IDHABILITACAOFILIAL = MPL.IDHABILITACAOFILIAL
	INNER JOIN STURMADISC TD (NOLOCK) ON TD.IDTURMADISC = M.IDTURMADISC
	INNER JOIN STURNO TTD (NOLOCK) ON TTD.CODTURNO = TD.CODTURNO
	INNER JOIN SDISCIPLINA D (NOLOCK) ON D.CODDISC = TD.CODDISC
	INNER JOIN SSTATUS SM (NOLOCK) ON SM.CODSTATUS = M.CODSTATUS
	INNER JOIN STIPOMATRICULA TMTD (NOLOCK) ON TMTD.CODTIPOMAT = M.TIPOMAT
	INNER JOIN SSTATUS RS (NOLOCK) ON RS.CODSTATUS = M.CODSTATUSRES
