/*--
	Ligação com 20 tabelas
	Consulta SQL leva 49 segundos para terminar
	Adicionado o NOLOCK, entretanto o tempo caiu para 45 segundos, ainda inviável.
	Criado uma view mas a mesma ainda leva os 45 segundos.
	Criado tabela para agilizar a consulta, ainda demora 12 segundos.
	Adicionado o nolock na consulta da tabela Z_BIS_CUBO_CLASSISNET_TODOS_CURSOS, a mesma caiu de 12 para 10 segundos.
--*/

SELECT * FROM Z_BIS_CUBO_CLASSISNET_TODOS_CURSOS (nolock)

CREATE TABLE Z_BIS_CUBO_CLASSISNET_TODOS_CURSOS(
	RA INT, --1
	NOMEALUNO VARCHAR(200), --2
	NOMECURSO VARCHAR(200), --3
	STATUSCURSO VARCHAR(50), --4
	TURNO VARCHAR(25), --5
	HABILITACAO VARCHAR(150), --6
	MATRIZCURRICULAR VARCHAR(100), --7
	SEMESTRE VARCHAR(25), --8
	PERIODOLETIVO VARCHAR(10), --9
	TURMAPERIODOLETIVO VARCHAR(15), --10
	TIPOMATRICULAPERIODOLETIVO VARCHAR(50), --11
	STATUSPERIODOLETIVO VARCHAR(50), --12
	TURMADISCIPLINA VARCHAR(15), --13
	TURNODISCIPLINA VARCHAR(25), --14
	CODDISCIPLINA VARCHAR(20), --15
	NOMEDISCIPLINA VARCHAR(200), --16
	STATUSDISCIPLINA VARCHAR(50), --17
	TIPOMATDISCIPLINA VARCHAR(50), --18
	RESULTADOFINAL VARCHAR(50), --19
	NUMERODIARIO INT, --20
	QTDE INT, --21
)


INSERT INTO Z_BIS_CUBO_CLASSISNET_TODOS_CURSOS
SELECT
	A.RA, --1
	P.NOME AS NOME_ALUNO, --2
	C.NOME AS NOME_CURSO, --3
	SC.DESCRICAO AS STATUS_CURSO, --4
	T.NOME AS TURNO, --5
	H.NOME AS HABILITACAO, --6
	G.DESCRICAO AS MATRIZ_CURRICULAR, --7
	CONVERT(VARCHAR(10), MPL.PERIODO) + ' Semestre' AS SEMESTRE, --8
	PL.CODPERLET AS PERIODO_LETIVO, --9
	MPL.CODTURMA AS TURMA_PERIODO_LETIVO, --10
	TM.DESCRICAO  AS TIPO_MATRICULA_PERIODO_LETIVO, --11
	SPL.DESCRICAO AS STATUS_PERIODO_LETIVO, --12
	TD.CODTURMA AS TURMA_DISCIPLINA, --13
	TTD.NOME AS TURNO_DISCIPLINA, --14
	D.CODDISC AS CODIGO_DISCIPLINA, --15
	D.NOME NOME_DISCIPLINA, --16
	SM.DESCRICAO AS STATUS_DISCIPLINA, --17
	TMTD.DESCRICAO AS TIPO_MATRICULA_DISCIPLINA, --18
	RS.DESCRICAO AS RESULTADO_FINAL, --19
	M.NUMDIARIO AS NUMERO_DIARIO, --20
	1 AS QUANTIDADE --21
FROM
	/*-- Dados do aluno --*/ 
	SALUNO A
	INNER JOIN PPESSOA P (NOLOCK) ON P.CODIGO = A.CODPESSOA
	/*-- Dados da matricula no curso --*/
	INNER JOIN SHABILITACAOALUNO HA (NOLOCK) ON HA.RA = A.RA
	INNER JOIN SSTATUS SC (NOLOCK) ON SC.CODSTATUS = HA.CODSTATUS
	INNER JOIN SHABILITACAOFILIAL HF (NOLOCK) ON HF.IDHABILITACAOFILIAL = HA.IDHABILITACAOFILIAL
	INNER JOIN SCURSO C (NOLOCK) ON C.CODCURSO = HF.CODCURSO
	INNER JOIN STURNO T (NOLOCK) ON T.CODTURNO = HF.CODTURNO
	INNER JOIN SHABILITACAO H (NOLOCK) ON H.CODCURSO = HF.CODCURSO AND H.CODHABILITACAO = HF.CODHABILITACAO
	INNER JOIN SGRADE G (NOLOCK) ON G.CODCURSO = HF.CODCURSO AND G.CODHABILITACAO = HF.CODHABILITACAO 
					AND G.CODGRADE = HF.CODGRADE AND APLICACAO = 'S' /*S - CLASSIS.NET*/
	/*-- dados da matricula no período letivo --*/
	LEFT JOIN SMATRICPL MPL (NOLOCK) ON MPL.RA = HA.RA AND MPL.IDHABILITACAOFILIAL = HA.IDHABILITACAOFILIAL
	INNER JOIN SPLETIVO PL (NOLOCK) ON PL.IDPERLET = MPL.IDPERLET
	INNER JOIN STIPOMATRICULA TM (NOLOCK) ON TM.CODTIPOMAT = MPL.CODTIPOMAT
	INNER JOIN SSTATUS SPL (NOLOCK) ON SPL.CODSTATUS = MPL.CODSTATUS
	/*-- Dados da matricula na disciplina --*/
	LEFT JOIN SMATRICULA M (NOLOCK) ON M.RA = MPL.RA AND M.IDPERLET = MPL.IDPERLET AND M.IDHABILITACAOFILIAL = MPL.IDHABILITACAOFILIAL
	INNER JOIN STURMADISC TD (NOLOCK) ON TD.IDTURMADISC = M.IDTURMADISC
	INNER JOIN STURNO TTD (NOLOCK) ON TTD.CODTURNO = TD.CODTURNO
	INNER JOIN SDISCIPLINA D (NOLOCK) ON D.CODDISC = TD.CODDISC
	INNER JOIN SSTATUS SM (NOLOCK) ON SM.CODSTATUS = M.CODSTATUS
	INNER JOIN STIPOMATRICULA TMTD (NOLOCK) ON TMTD.CODTIPOMAT = M.TIPOMAT
	INNER JOIN SSTATUS RS (NOLOCK) ON RS.CODSTATUS = M.CODSTATUSRES
